# Generated by Django 6.0.4 on 2026-04-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('nodule_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de nodules')),
                ('max_probability', models.FloatField(default=0.0, verbose_name='Probabilité max')),
                ('niveau_risque', models.CharField(blank=True, max_length=20, verbose_name='Niveau de risque')),
                ('slices_dir', models.CharField(blank=True, max_length=500, verbose_name='Dossier slices')),
                ('erreur', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='dossiers.dossier', verbose_name='Dossier')),
                ('fichier_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='dossiers.fichiermedical', verbose_name='Fichier analysé')),
            ],
            options={
                'verbose_name': 'Analyse',
                'db_table': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordX', models.FloatField(verbose_name='Coordonnée X')),
                ('coordY', models.FloatField(verbose_name='Coordonnée Y')),
                ('coordZ', models.FloatField(verbose_name='Coordonnée Z')),
                ('diameter_mm', models.FloatField(verbose_name='Diamètre (mm)')),
                ('probability', models.FloatField(verbose_name='Probabilité de malignité')),
                ('risk', models.CharField(choices=[('FAIBLE', 'Faible'), ('MODERE', 'Modéré'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], max_length=10, verbose_name='Niveau de risque')),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodules', to='analyse.analyse', verbose_name='Analyse')),
            ],
            options={
                'verbose_name': 'Nodule',
                'db_table': 'nodules',
                'ordering': ['-probability'],
            },
        ),
    ]
