# Generated by Django 6.0.5 on 2026-06-19 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctscan', '0005_remove_nodule_ebox_x_remove_nodule_ebox_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoduleSegmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodule_id_ticnet', models.IntegerField(verbose_name='ID Nodule TiCNet')),
                ('rang', models.PositiveIntegerField(verbose_name='Rang (par probabilité)')),
                ('voxel_x', models.FloatField()),
                ('voxel_y', models.FloatField()),
                ('voxel_z', models.FloatField()),
                ('diametre_ticnet_mm', models.FloatField(verbose_name='Diamètre TiCNet (mm)')),
                ('diametre_seg_mm', models.FloatField(verbose_name='Diamètre segmenté (mm)')),
                ('volume_mm3', models.FloatField(verbose_name='Volume (mm³)')),
                ('n_voxels', models.IntegerField(verbose_name='Nombre de voxels du masque')),
                ('mask_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin masque .npy')),
                ('ct_crop_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin crop .npy')),
                ('ct_image_path', models.CharField(blank=True, max_length=500, verbose_name='PNG CT crop')),
                ('mask_image_path', models.CharField(blank=True, max_length=500, verbose_name='PNG masque')),
                ('contour_image_path', models.CharField(blank=True, max_length=500, verbose_name='PNG contour')),
                ('mesh_path', models.CharField(blank=True, max_length=500, verbose_name='Mesh 3D JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentations', to='ctscan.ctscan', verbose_name='CT Scan')),
            ],
            options={
                'verbose_name': 'Segmentation de nodule',
                'db_table': 'nodule_segmentations',
                'ordering': ['scan', 'rang'],
                'constraints': [models.UniqueConstraint(fields=('scan', 'nodule_id_ticnet'), name='unique_segmentation_par_nodule')],
            },
        ),
    ]
