# Generated by Django 6.0.5 on 2026-06-19 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctscan', '0005_remove_nodule_ebox_x_remove_nodule_ebox_y_and_more'),
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodulesegmentation',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='nodulesegmentation',
            name='unique_segmentation_par_nodule',
        ),
        migrations.AlterUniqueTogether(
            name='nodulesegmentation',
            unique_together={('scan', 'nodule_id_ticnet')},
        ),
        migrations.AddField(
            model_name='nodulesegmentation',
            name='center_mm',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='nodulesegmentation',
            name='center_voxel',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='nodulesegmentation',
            name='diam_seg_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nodulesegmentation',
            name='diam_ticnet_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nodulesegmentation',
            name='mask_npy_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nodulesegmentation',
            name='mesh_json_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nodulesegmentation',
            name='rpn_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nodulesegmentation',
            name='contour_image_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nodulesegmentation',
            name='ct_image_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nodulesegmentation',
            name='mask_image_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nodulesegmentation',
            name='n_voxels',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nodulesegmentation',
            name='nodule_id_ticnet',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nodulesegmentation',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentations', to='ctscan.ctscan'),
        ),
        migrations.AlterField(
            model_name='nodulesegmentation',
            name='volume_mm3',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='nodulesegmentation',
            name='ct_crop_path',
        ),
        migrations.RemoveField(
            model_name='nodulesegmentation',
            name='diametre_seg_mm',
        ),
        migrations.RemoveField(
            model_name='nodulesegmentation',
            name='diametre_ticnet_mm',
        ),
        migrations.RemoveField(
            model_name='nodulesegmentation',
            name='mask_path',
        ),
        migrations.RemoveField(
            model_name='nodulesegmentation',
            name='mesh_path',
        ),
        migrations.RemoveField(
            model_name='nodulesegmentation',
            name='rang',
        ),
        migrations.RemoveField(
            model_name='nodulesegmentation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='nodulesegmentation',
            name='voxel_x',
        ),
        migrations.RemoveField(
            model_name='nodulesegmentation',
            name='voxel_y',
        ),
        migrations.RemoveField(
            model_name='nodulesegmentation',
            name='voxel_z',
        ),
    ]
