# Generated by Django 6.0.5 on 2026-06-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctscan', '0005_remove_nodule_ebox_x_remove_nodule_ebox_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoduleClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodule_id_ticnet', models.IntegerField(help_text='ID du nodule dans la table Nodule')),
                ('rang', models.PositiveIntegerField()),
                ('voxel_x', models.FloatField()),
                ('voxel_y', models.FloatField()),
                ('voxel_z', models.FloatField()),
                ('diametre_mm', models.FloatField(blank=True, null=True)),
                ('prob_detection', models.FloatField(blank=True, help_text="Probabilité TiCNet (champ 'probabilite')", null=True)),
                ('label', models.IntegerField(choices=[(0, 'Benigne'), (1, 'Maligne')])),
                ('proba_maligne', models.FloatField()),
                ('proba_benigne', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='ctscan.ctscan')),
            ],
            options={
                'db_table': 'nodule_classifications',
                'ordering': ['scan', 'rang'],
                'unique_together': {('scan', 'nodule_id_ticnet')},
            },
        ),
    ]
