# Generated by Django 6.0.4 on 2026-04-19 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Dossier',
                'db_table': 'dossiers',
            },
        ),
        migrations.CreateModel(
            name='FichierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fichier', models.CharField(choices=[('CT', 'CT Scan'), ('XRAY', 'Radio X-Ray'), ('AUTRE', 'Autre')], max_length=10, verbose_name='Type de fichier')),
                ('fichier', models.FileField(upload_to='dossiers/%Y/%m/', verbose_name='Fichier')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Fichier Médical',
                'db_table': 'fichiers_medicaux',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'analyse"), ('ANALYSE', 'Analysé'), ('FINALISE', 'Finalisé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('resultat_ia', models.TextField(blank=True, verbose_name='Résultat IA')),
                ('notes_medecin', models.TextField(blank=True, verbose_name='Notes du médecin')),
                ('conclusion', models.TextField(blank=True, verbose_name='Conclusion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Rapport',
                'db_table': 'rapports',
            },
        ),
    ]
