# Generated by Django 6.0.4 on 2026-04-19 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_doctor_email_user_email_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('age', models.PositiveIntegerField(verbose_name='Âge')),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Sexe')),
                ('telephone', models.CharField(max_length=20, verbose_name='N° Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.doctor', verbose_name='Médecin responsable')),
            ],
            options={
                'verbose_name': 'Patient',
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
