# Generated by Django 6.0.5 on 2026-06-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='historique_medical',
            field=models.TextField(blank=True, default='', verbose_name='Historique médical'),
        ),
    ]
