# Generated by Django 6.0.5 on 2026-05-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_mhd', models.FileField(upload_to='ctscans/%Y/%m/', verbose_name='Fichier .mhd')),
                ('fichier_raw', models.FileField(upload_to='ctscans/%Y/%m/', verbose_name='Fichier .raw')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', "En cours d'analyse"), ('TERMINE', 'Terminé'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('origin_z', models.FloatField(blank=True, null=True)),
                ('origin_y', models.FloatField(blank=True, null=True)),
                ('origin_x', models.FloatField(blank=True, null=True)),
                ('spacing_z', models.FloatField(blank=True, null=True)),
                ('spacing_y', models.FloatField(blank=True, null=True)),
                ('spacing_x', models.FloatField(blank=True, null=True)),
                ('message_erreur', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('duree_analyse', models.FloatField(blank=True, null=True, verbose_name='Durée (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctscans', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'CT Scan',
                'db_table': 'ctscans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.PositiveIntegerField(verbose_name='Rang (par probabilité)')),
                ('monde_z', models.FloatField(verbose_name='Coordonnée monde Z (mm)')),
                ('monde_y', models.FloatField(verbose_name='Coordonnée monde Y (mm)')),
                ('monde_x', models.FloatField(verbose_name='Coordonnée monde X (mm)')),
                ('voxel_z', models.FloatField(verbose_name='Voxel Z')),
                ('voxel_y', models.FloatField(verbose_name='Voxel Y')),
                ('voxel_x', models.FloatField(verbose_name='Voxel X')),
                ('diametre_mm', models.FloatField(verbose_name='Diamètre estimé (mm)')),
                ('probabilite', models.FloatField(verbose_name='Probabilité de malignité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ctscan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodules', to='ctscan.ctscan', verbose_name='CT Scan')),
            ],
            options={
                'verbose_name': 'Nodule',
                'db_table': 'nodules',
                'ordering': ['ctscan', 'rang'],
            },
        ),
    ]
