# Generated by Django 6.0.5 on 2026-06-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctscan',
            name='fichier_mhd_seg',
            field=models.FileField(blank=True, null=True, upload_to='ctscans/%Y/%m/', verbose_name='Fichier .mhd preprocessé'),
        ),
        migrations.AddField(
            model_name='ctscan',
            name='fichier_raw_seg',
            field=models.FileField(blank=True, null=True, upload_to='ctscans/%Y/%m/', verbose_name='Fichier .raw preprocessé'),
        ),
    ]
