# Generated by Django 6.0.5 on 2026-06-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctscan', '0002_ctscan_fichier_mhd_seg_ctscan_fichier_raw_seg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctscan',
            name='fichier_mhd_seg',
        ),
        migrations.RemoveField(
            model_name='ctscan',
            name='fichier_raw_seg',
        ),
    ]
