# Generated by Django 6.0.5 on 2026-06-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctscan', '0003_remove_ctscan_fichier_mhd_seg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodule',
            name='ebox_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodule',
            name='ebox_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodule',
            name='ebox_z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
