# Generated by Django 6.0.5 on 2026-06-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctscan', '0004_nodule_ebox_x_nodule_ebox_y_nodule_ebox_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodule',
            name='ebox_x',
        ),
        migrations.RemoveField(
            model_name='nodule',
            name='ebox_y',
        ),
        migrations.RemoveField(
            model_name='nodule',
            name='ebox_z',
        ),
        migrations.AddField(
            model_name='ctscan',
            name='ebox_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctscan',
            name='ebox_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctscan',
            name='ebox_z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
